### ISSUE TITLE
Integrating with the tsibble package

### ISSUE THREAD

**Issue by aspina7** [reconhub/aweek#34]
Hey - know you are swamped, but just thought I would flag this here as an fyi. 

Might be worth integrating aweek in to the tsibble package. Have posted an [issue ](https://github.com/tidyverts/tsibble/issues/205#issue-650391831) on the tsibble page too. 

It's a pretty functional package (with a yearweek function) - have been using it for time series analysis. 

This would also address @jpolonsky issues ([1](https://github.com/reconhub/aweek/issues/27) and [2](https://github.com/reconhub/aweek/issues/28)) - because with tsibble can do both those in regular dplyr syntax. 

Long shot but would also make the incidence package a lot simpler (i think) 

Anyway - food for thought nothing actionable! 

have a good one

**Comment by zkamvar** [comment]
Looks like they took care of it using {lubridate}: https://github.com/tidyverts/tsibble/commit/41fdbf7ec3dce66b0b82d7ceb16a5f6caaec2793, which makes sense since they already imported it from the get-go. Their criticism that {aweek} doesn't natively support the `+` operator is fair. Honestly, I didn't even know that {lubridate} had that feature until after I built {aweek}, and now that I know about it, I'm reluctant to build any more functionality into this since It's just reinventing the wheel.

**Comment by aspina7** [comment]
Agree - guess leave as is considering incidence2 being built of back of aweek
